version: '2'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'bridge'
    ports:
      - '8096:8096'
      - '8920:8920'
    volumes:
      - /mnt/SSD/jellyfin/config:/config
      - /mnt/SSD/jellyfin/cache:/cache
      - /mnt/SSD/NextCloud/data/user/files/Music:/media
    restart: 'unless-stopped'
